# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/templates
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)/functions
    includeRootFolder: false

- task: PublishBuildArtifacts@1